[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit files"]

[tasks.clean]
command = "rm"
args = [
  "-r",
  "--force",
  "./out/"
]

[tasks.build]
command = "zig"
args = [
   "build-", 
   "-Z", 
   "unstable-options", 
   "--verbose"
]
dependencies = ["clean"]

[tasks.build_kernel]
command = "zig"
args = [
  "build-lib",
  "--name",
  ""
]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.flow]
dependencies = [
   "format",
   "build",
   "test",
]
